services:
  - type: web
    name: sistema-reportes
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn reportes.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    staticPublishPath: static/
    plan: free
